import type { PartialMessageCatalogue } from '@/components/import-wizard';
import { ITALIAN as FEATURES_ITALIAN } from './features/italian';

const n = (count: number) => count.toLocaleString('it-IT');
const righe = (count: number) => (count === 1 ? '1 riga' : `${n(count)} righe`);

/**
 * The Italian catalogue the prototype passes to the wizard, as SpeakArt would
 * from its own translations. Covers upload, mapping, the review and the report.
 */
export const PROTO_ITALIAN: PartialMessageCatalogue = {
  ...FEATURES_ITALIAN,
  steps: {
    upload: 'Caricamento',
    mapping: 'Abbina colonne',
    review: 'Revisione',
    resolution: 'Collega anagrafiche',
    import: 'Importazione',
  },
  upload: {
    helpText: 'Carica un foglio con i nomi delle colonne nella prima riga e un’opera per riga.',
    dropHere: 'Rilascia qui il file',
    dragAndDrop: 'Trascina qui un file',
    accepted: 'Puoi caricare: {types} (fino a {maxSize})',
    chooseFile: 'Scegli un file',
  },
  mapping: {
    title: 'Abbina le colonne',
    description: 'Abbina le colonne del tuo file ai campi previsti',
    mappedCount: '{mapped}/{total} abbinate',
    autoMatched: 'Alcune colonne sono state abbinate automaticamente. Controlla e correggi se serve.',
    autoBadge: 'Auto',
    selectField: 'Scegli il campo…',
    doNotImport: 'Non importare',
    missingRequired: 'Campi obbligatori non abbinati: {fields}',
    uncertainBadge: 'Da verificare',
    confirmMatch: 'Conferma',
    uncertainPending: ({ count }) =>
      `${count === 1 ? '1 colonna' : `${n(count)} colonne`} da verificare: conferma l’abbinamento o scegli un altro campo`,
    continue: 'Continua alla revisione',
  },
  review: {
    title: 'Revisione dei dati',
    description: 'Correggi ciò che blocca l’importazione direttamente nella griglia',
    rowCount: ({ count }) => righe(count),
    rowCountFiltered: ({ visible, total }) => `${n(visible)} di ${righe(total)}`,
    filterAll: ({ count }) => `Tutte ${n(count)}`,
    filterErrors: ({ count }) => `Bloccate ${n(count)}`,
    filterWarnings: ({ count }) => `Con avvisi ${n(count)}`,
    filterExcluded: ({ count }) => `Escluse ${n(count)}`,
    importableCount: ({ count }) => `${count === 1 ? '1 riga sarà importata' : `${n(count)} righe saranno importate`}`,
    noSearchMatches: 'Nessuna riga corrisponde alla ricerca',
    noFilterMatches: 'Nessuna riga corrisponde al filtro',
    rowNumberHeader: '#',
    statusHeader: 'Stato',
    summaryBlocked: ({ count }) => `${righe(count)} da correggere prima di importare`,
    summaryClear: 'Nessun problema blocca l’importazione',
    summaryRows: ({ count }) => righe(count),
    summaryFix: 'Correggi',
    summaryReview: 'Rivedi',
    summaryMore: ({ count }) => `Mostra altri ${n(count)}`,
    summaryLess: 'Mostra meno',
    warningsTitle: ({ count }) =>
      `${count === 1 ? '1 avviso' : `${n(count)} avvisi`} · non bloccano l’importazione`,
    acceptNotes: 'Segna tutti come visti',
    notesAccepted: ({ count }) => `${count === 1 ? '1 avviso segnato' : `${n(count)} avvisi segnati`} come visti`,
    undoAcceptNotes: 'Annulla',
    groupRequired: '{field} mancante',
    groupNotAnOption: '{field}: valore non riconosciuto',
    groupInvalidNumber: '{field}: non è un numero',
    groupInvalidDate: '{field}: data non riconosciuta',
    groupAmbiguousNumber: '{field}: numero da verificare',
    groupOther: '{field}: {message}',
    guideLabel: 'In correzione',
    guideRows: ({ count }) => righe(count),
    guideShowAll: 'Mostra tutte le righe',
    guideRequired: 'Manca il valore di «{field}». Inseriscilo in ciascuna cella evidenziata.',
    guideNotAnOption: '«{value}» non è tra i valori ammessi per {field}. Scegline uno dall’elenco.',
    guideInvalidNumber: '«{value}» contiene testo. Inserisci un numero, ad esempio {example}, verificando il valore da registrare.',
    guideInvalidNumberNoExample: '«{value}» non è un numero. Scrivilo in cifre.',
    guideInvalidDate: '«{value}» non è una data. Scrivila come {format} oppure AAAA-MM-GG.',
    guideAmbiguousNumber: '{text} è stato letto come {value}. Se intendevi un altro numero, correggi la cella.',
    guideOther: '{message}',
    guideNotBlocking: 'Non blocca l’importazione.',
    guideValueRows: ({ value, count }) => `«${value}» · ${righe(count)}`,
    guideChoose: 'Valore da usare al posto di «{value}»',
    guideChoosePlaceholder: 'Scegli il valore',
    guideApply: ({ value, replacement, count }) => `Sostituisci «${value}» con «${replacement}» in ${righe(count)}`,
    guideApplyPending: ({ count }) => `Applica a ${righe(count)}`,
    guideEachCell: 'Puoi anche modificare singolarmente le celle evidenziate.',
    guideFirst: 'Vai alla prima cella da correggere',
    guideNext: 'Cella successiva',
    guideGoToRow: 'Vai alla riga {row}',
    guideExclude: ({ count }) => (count === 1 ? 'Escludi questa riga' : `Escludi queste ${n(count)} righe`),
    guideExcludeHint: 'Le righe escluse non vengono importate; puoi includerle di nuovo in qualsiasi momento.',
    guideResolved: 'Problema risolto',
    guideNextProblem: 'Problema successivo',
    guideUndo: 'Annulla',
    blockedHint: ({ count }) => `Correggi o escludi prima ${righe(count)}`,
    statusErrors: ({ count }) => (count === 1 ? '1 errore' : `${n(count)} errori`),
    statusWarnings: ({ count }) => (count === 1 ? '1 avviso' : `${n(count)} avvisi`),
    statusOk: 'Nessun problema',
    excludeRow: 'Escludi la riga {row}',
    includeRow: 'Includi la riga {row}',
    excludeRowHint: 'Lascia questa riga fuori dall’importazione',
    includeRowHint: 'Includi di nuovo questa riga nell’importazione',
    excludedStatus: 'Esclusa',
    cellLabel: '{field}, riga {row}',
    excludeErrors: 'Escludi righe bloccate',
    excludeErrorsHint: 'Lascia fuori dall’importazione tutte le righe che hanno ancora errori',
    fillRequired: 'Compila obbligatori',
    fillRequiredHint: 'Riempi i campi obbligatori vuoti con un valore segnaposto',
    fillPlaceholder: 'N/D',
    undo: 'Annulla (Ctrl+Z)',
    redo: 'Ripeti (Ctrl+Maiusc+Z)',
    back: 'Torna all’abbinamento',
    excludedCount: ({ count }) => (count === 1 ? '1 esclusa' : `${n(count)} escluse`),
    complete: ({ count }) => `Importa ${righe(count)}`,
    continueToResolution: ({ count }) => `Collega le anagrafiche (${righe(count)})`,
  },
  commit: {
    title: 'Importazione in corso',
    progress: ({ done, total }) => `${n(done)} di ${righe(total)} elaborate`,
    progressLabel: 'Avanzamento dell’importazione',
    keepOpen: 'Tieni aperta questa pagina finché l’importazione non è finita.',
  },
  cell: { empty: 'vuota', clear: 'Svuota', save: 'Salva', cancel: 'Annulla' },
  search: {
    placeholder: 'Cerca nei dati…',
    clear: 'Cancella la ricerca',
    matchCount: ({ count }) => (count === 1 ? '1 risultato' : `${n(count)} risultati`),
  },
  findReplace: {
    open: 'Trova e sostituisci',
    title: 'Trova e sostituisci',
    description: 'Cerca e sostituisci testo in tutte le celle. Usa Ctrl+Invio per sostituire.',
    find: 'Trova',
    findPlaceholder: 'Testo da trovare…',
    replace: 'Sostituisci con',
    replacePlaceholder: 'Testo sostitutivo (vuoto per cancellare)',
    column: 'Nella colonna',
    allColumns: 'Tutte le colonne',
    caseSensitive: 'Maiuscole/minuscole',
    wholeWord: 'Parola intera',
    willUpdate: ({ count }) => (count === 1 ? 'Verrà aggiornata 1 cella' : `Verranno aggiornate ${n(count)} celle`),
    noMatches: 'Nessun risultato',
    replaced: ({ count }) => (count === 1 ? 'Sostituita 1 cella' : `Sostituite ${n(count)} celle`),
    close: 'Chiudi',
    replaceAll: 'Sostituisci tutto',
  },
  export: {
    menu: 'Esporta',
    csv: 'Esporta in CSV',
    excel: 'Esporta in Excel',
    validOnly: 'Esporta solo le righe importabili (Excel)',
  },
  validation: {
    required: '{field}: manca il valore',
    invalidDate: '{field}: data non riconosciuta (usa {format} o AAAA-MM-GG)',
    invalidNumber: '{field}: non è un numero',
    ambiguousNumber: '{field}: {text} letto come {value}, da verificare',
    notAnOption: '{field}: valore non tra quelli ammessi ({options})',
    notAnOptionAndMore: '{field}: valore non tra quelli ammessi ({options} e altri {more})',
  },
};
